<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="What the cassava leaf data show about predicting leaf δ13C from mid-infrared spectra, and how to validate such models">

<title>Predicting δ13C from MIR spectra: findings – cassava</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-cbed26e0df856eae0d97ab8ae9893fbb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Predicting δ13C from MIR spectra: findings – cassava">
<meta property="og:description" content="What the cassava leaf data show about predicting leaf δ13C from mid-infrared spectra, and how to validate such models">
<meta property="og:image" content="https://franckalbinet.github.io/cassava/images/c13_by_batch.png">
<meta property="og:site_name" content="cassava">
<meta property="og:image:alt" content="Box plot of δ13C by batch">
<meta property="og:image:height" content="846">
<meta property="og:image:width" content="1181">
<meta name="twitter:title" content="Predicting δ13C from MIR spectra: findings – cassava">
<meta name="twitter:description" content="What the cassava leaf data show about predicting leaf δ13C from mid-infrared spectra, and how to validate such models">
<meta name="twitter:image" content="https://franckalbinet.github.io/cassava/images/c13_by_batch.png">
<meta name="twitter:image:alt" content="Box plot of δ13C by batch">
<meta name="twitter:image-height" content="846">
<meta name="twitter:image-width" content="1181">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">cassava</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./report.html">Report</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./report.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Report</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PLS baseline</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">API reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">data</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#why-δ13c" id="toc-why-δ13c" class="nav-link" data-scroll-target="#why-δ13c">Why δ13C</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#batch-structure" id="toc-batch-structure" class="nav-link" data-scroll-target="#batch-structure">Batch structure</a></li>
  <li><a href="#data-quality-water-vapour" id="toc-data-quality-water-vapour" class="nav-link" data-scroll-target="#data-quality-water-vapour">Data quality: water vapour</a></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation">Validation</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#global-pls-model" id="toc-global-pls-model" class="nav-link" data-scroll-target="#global-pls-model">Global PLS model</a></li>
  <li><a href="#within-batch-models" id="toc-within-batch-models" class="nav-link" data-scroll-target="#within-batch-models">Within-batch models</a></li>
  </ul></li>
  <li><a href="#what-this-means-for-each-use-case" id="toc-what-this-means-for-each-use-case" class="nav-link" data-scroll-target="#what-this-means-for-each-use-case">What this means for each use case</a></li>
  <li><a href="#open-questions-and-next-steps" id="toc-open-questions-and-next-steps" class="nav-link" data-scroll-target="#open-questions-and-next-steps">Open questions and next steps</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/franckalbinet/cassava/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.html.md"><i class="bi bi-file-code"></i>Markdown</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting δ13C from MIR spectra: findings</h1>
</div>

<div>
  <div class="description">
    What the cassava leaf data show about predicting leaf δ13C from mid-infrared spectra, and how to validate such models
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->
<p><strong>Work in progress.</strong> The analysis isn’t finished. The findings below come from a first round of models, and the growing conditions of the batches are still missing. Expect the results and conclusions to change.</p>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>A PLS model on the MIR spectra reaches an R² of 0.77 on a random split stratified by batch. Batch identity alone reaches an R² of 0.68 on the same data. The spectra add little to what the batch already tells us.</p>
<p>The model can’t predict the δ13C level of a batch it hasn’t seen. Under leave-one-batch-out validation, its R² is -0.01.</p>
<p>Inside batches, the spectra carry real δ13C information. A local PLS model, calibrated on samples from one batch, explains 36% to 73% of the δ13C variation inside that batch. This holds for six of the seven batches. Batch 1592 shows no signal.</p>
<p>MIRS can rank samples within a trial when some samples from that trial have lab values. It can’t replace lab measurements for a new trial.</p>
</section>
<section id="why-δ13c" class="level2">
<h2 class="anchored" data-anchor-id="why-δ13c">Why δ13C</h2>
<p>Cassava is a C3 plant. During photosynthesis, its carbon-fixing enzyme, Rubisco, fixes CO2 that contains the light isotope 12C more readily than CO2 that contains 13C. How strongly the leaf favours 12C depends on the CO2 concentration inside the leaf, compared with the air outside.</p>
<p>A plant short of water closes its stomata to save water. The CO2 concentration inside the leaf then falls, and the leaf favours 12C less. Its δ13C rises, which means it becomes less negative.</p>
<p>Leaf δ13C therefore records the balance between carbon gain and water loss while the leaf grew. Plant scientists use it as a measure of water-use efficiency and of a plant’s response to water stress. In wheat, for example, breeders have used it to select varieties that use water more efficiently.</p>
<p>Measuring δ13C needs isotope-ratio mass spectrometry, which is slow and costly for each sample. MIR spectra are fast and cheap to collect. A model that predicts δ13C from spectra would let breeders and physiologists screen many more plants.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>The spectra file <code>specs_trim.csv</code> holds absorbance spectra of 1184 samples. Each spectrum has 1711 points from 651.8 to 3949.5 cm⁻¹, about 1.93 cm⁻¹ apart. The file <code>all_batches_wet_chem.csv</code> holds δ13C values for 1291 samples. 1158 samples appear in both files, and all the analyses use these 1158 samples.</p>
<p>Sample ids have the form <code>&lt;batch&gt;_&lt;sample&gt;</code>. Each of the seven batches is a set of plants grown under its own conditions and scanned at its own time, on the same spectrometer. The data don’t record the conditions.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Batch</th>
<th>Samples</th>
<th>Mean δ13C (‰)</th>
<th>Standard deviation (‰)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1456</td>
<td>149</td>
<td>-23.85</td>
<td>1.20</td>
</tr>
<tr class="even">
<td>1586</td>
<td>168</td>
<td>-28.87</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td>1592</td>
<td>244</td>
<td>-26.06</td>
<td>0.85</td>
</tr>
<tr class="even">
<td>1597</td>
<td>97</td>
<td>-28.11</td>
<td>0.78</td>
</tr>
<tr class="odd">
<td>1678</td>
<td>144</td>
<td>-25.56</td>
<td>1.62</td>
</tr>
<tr class="even">
<td>1722</td>
<td>177</td>
<td>-28.54</td>
<td>1.11</td>
</tr>
<tr class="odd">
<td>1723</td>
<td>179</td>
<td>-27.36</td>
<td>1.26</td>
</tr>
</tbody>
</table>
<p><img src="images/c13_by_batch.png" alt="Box plot of δ13C by batch" width="80%" style="display: block; margin: 0 auto;"></p>
<p>δ13C by batch. The batch means differ by up to 5 ‰.</p>
</section>
<section id="batch-structure" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="batch-structure">Batch structure</h2>
<p>Batch explains 68% of the δ13C variance. This is the between-batch share of the variance (η²). The batch means span 5 ‰, from -28.87 ‰ in batch 1586 to -23.85 ‰ in batch 1456. Inside a batch, the standard deviation is 0.78 to 1.62 ‰.</p>
<p>The spectra also differ between batches. In a PCA of the raw spectra, the first component explains 92.6% of the variance. It reflects overall absorbance and baseline, and it doesn’t correlate with δ13C (r = 0.00). SNV removes this effect, and the separate cluster of batch 1678 in the raw PCA disappears. After SNV and a Savitzky-Golay first derivative, five batches overlap in one core. Batches 1722 and 1723 lie along a separate arm. On the first component of these spectra, batch explains 80% of the variance (η² = 0.80). The arm comes from band shapes across the fingerprint region, with the largest loading at 1250 cm⁻¹. Inside batches 1722 and 1723, the position along the arm doesn’t follow δ13C (r = -0.05 and 0.06).</p>
<p>The PCA plots and loadings are in the <a href="./eda.html">EDA notebook</a>.</p>
<div class="column-page">
<p><img src="images/pca_by_batch.png" alt="PCA scores coloured by batch, for raw, SNV and SNV plus first-derivative spectra" width="100%"></p>
</div>
<p>First two PCA components of the raw spectra, the SNV spectra and the SNV first-derivative spectra (<code>snv_sg1</code>), coloured by batch. In the <code>snv_sg1</code> panel, the horizontal arm holds batches 1722 and 1723, and the vertical arm holds samples with water vapour.</p>
</section>
<section id="data-quality-water-vapour" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-water-vapour">Data quality: water vapour</h2>
<p>Some spectra contain water vapour lines. These are sharp, regular lines between about 3900 and 3550 cm⁻¹, with weaker ones between 1800 and 1300 cm⁻¹. They come from humidity in the beam path, not from the leaves.</p>
<p>We measured them with a water vapour index. The index takes each SNV spectrum, subtracts a Savitzky-Golay smoothed copy (11-point window), and returns the standard deviation of the residual between 3550 and 3900 cm⁻¹. It correlates with the second PCA component of the derivative spectra at r = 0.92. That component is therefore water vapour, not leaf chemistry.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Batch</th>
<th>Samples above 3 times the median index</th>
<th>Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1456</td>
<td>0</td>
<td>0%</td>
</tr>
<tr class="even">
<td>1586</td>
<td>0</td>
<td>0%</td>
</tr>
<tr class="odd">
<td>1592</td>
<td>27</td>
<td>11%</td>
</tr>
<tr class="even">
<td>1597</td>
<td>57</td>
<td>59%</td>
</tr>
<tr class="odd">
<td>1678</td>
<td>4</td>
<td>3%</td>
</tr>
<tr class="even">
<td>1722</td>
<td>6</td>
<td>3%</td>
</tr>
<tr class="odd">
<td>1723</td>
<td>2</td>
<td>1%</td>
</tr>
</tbody>
</table>
<p>The threshold of 3 times the median is arbitrary. It shows how far the problem spreads.</p>
<p>Four samples from batch 1722 stand apart in the PCA because of water vapour: 1722_092, 1722_120, 1722_138 and 1722_147. Sample 1722_138 also has a weaker band near 1250 cm⁻¹ than the rest of its batch.</p>
<p>Removing everything above 3550 cm⁻¹ changed the model results only slightly. The lines between 1800 and 1300 cm⁻¹ are still in the spectra, because trimming there would also remove the amide bands.</p>
<p><img src="images/vapour_by_batch.png" alt="Box plot of the water vapour index by batch, on a log scale" width="80%" style="display: block; margin: 0 auto;"></p>
<p>Water vapour index by batch, on a log scale. Batch 1597 has the highest median.</p>
</section>
<section id="validation" class="level2">
<h2 class="anchored" data-anchor-id="validation">Validation</h2>
<p>A random split puts samples from every batch into both training and test folds. The model then learns where each batch sits, and the test score rewards it for that. With 68% of the variance between batches, a random split gives a high R² even when the spectra say little about δ13C itself.</p>
<p>We used three scores:</p>
<ul>
<li><strong>Random split</strong>, 5 folds stratified by batch. It tests predictions for new samples from batches the model has seen.</li>
<li><strong>Leave one batch out</strong>, 7 folds. It tests predictions for a batch the model has never seen.</li>
<li><strong>Within-batch R²</strong>. It centres the observed and predicted values on their batch means before computing R². A model that predicts only the batch means scores 0.</li>
</ul>
<p>We also report the correlation r between observed and predicted values inside each batch. It measures only the order of the predictions, and ignores their level and spread. For ranking samples within a trial, r is the score that matters.</p>
<p>The random-split R² splits into these parts. Batch explains 0.68 of the variance. The remaining 0.32 lies inside batches, and the model explains 0.29 of it. Together, 0.68 + 0.29 × 0.32 = 0.77, which matches the random-split R².</p>
<p>We recommend reporting the within-batch R² and the leave-one-batch-out score next to any random-split R².</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="global-pls-model" class="level3">
<h3 class="anchored" data-anchor-id="global-pls-model">Global PLS model</h3>
<p>The pipeline applies SNV, a Savitzky-Golay first derivative (15-point window, cubic polynomial) and PLS regression without feature scaling. We chose the number of components by the lowest RMSE on the same folds that score the model. This makes all scores below slightly optimistic.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Split</th>
<th>Components</th>
<th>R²</th>
<th>RMSE (‰)</th>
<th>Within-batch R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random</td>
<td>17</td>
<td>0.77</td>
<td>0.97</td>
<td>0.29</td>
</tr>
<tr class="even">
<td>Leave one batch out</td>
<td>20</td>
<td>-0.01</td>
<td>2.01</td>
<td>-0.19</td>
</tr>
</tbody>
</table>
<p>When a batch is left out, the model pulls its predictions towards the mean of the other batches. Batch 1456 has the highest mean, and the model predicts it 3.45 ‰ too low.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Held-out batch</th>
<th>Bias (‰)</th>
<th>Within-batch R²</th>
<th>r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1456</td>
<td>-3.45</td>
<td>0.13</td>
<td>0.42</td>
</tr>
<tr class="even">
<td>1586</td>
<td>1.41</td>
<td>0.48</td>
<td>0.70</td>
</tr>
<tr class="odd">
<td>1592</td>
<td>0.45</td>
<td>-1.39</td>
<td>-0.03</td>
</tr>
<tr class="even">
<td>1597</td>
<td>1.46</td>
<td>-1.08</td>
<td>0.12</td>
</tr>
<tr class="odd">
<td>1678</td>
<td>-1.38</td>
<td>-0.33</td>
<td>0.04</td>
</tr>
<tr class="even">
<td>1722</td>
<td>0.90</td>
<td>-0.15</td>
<td>0.58</td>
</tr>
<tr class="odd">
<td>1723</td>
<td>-0.78</td>
<td>0.27</td>
<td>0.61</td>
</tr>
</tbody>
</table>
<p>The model ranks four new batches moderately well, with r from 0.42 to 0.70. It has no ranking skill for batches 1592, 1597 and 1678. No number of components between 3 and 20 gives consistent ranking on new batches. For single batches, the within-batch R² changes sign as the number of components changes. Removing the region above 3550 cm⁻¹ changes the results only slightly.</p>
<p><img src="images/observed_predicted.png" alt="Observed against predicted δ13C for the full and trimmed spectra, on the random and leave-one-batch-out splits" width="100%" style="display: block; margin: 0 auto;"></p>
<p>Observed against predicted δ13C. The rows show the full and trimmed spectra. The columns show the random split and leave-one-batch-out. Under leave-one-batch-out, each batch’s predictions move towards the mean of the other batches.</p>
</section>
<section id="within-batch-models" class="level3">
<h3 class="anchored" data-anchor-id="within-batch-models">Within-batch models</h3>
<p>Two models learn only the variation inside batches. A local model is fitted on one batch, with 5-fold cross-validation inside it. The pooled model is fitted on all batches at once, after each batch is centred on its own mean spectrum and mean δ13C. Each fold computes the batch means from its training samples only. Both models need lab values from the batch they predict.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Within-batch R², global</th>
<th>Within-batch R², local</th>
<th>Within-batch R², pooled</th>
<th>r, global</th>
<th>r, local</th>
<th>r, pooled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1456</td>
<td>0.17</td>
<td>0.42</td>
<td>0.26</td>
<td>0.58</td>
<td>0.65</td>
<td>0.53</td>
</tr>
<tr class="even">
<td>1586</td>
<td>0.57</td>
<td>0.73</td>
<td>0.66</td>
<td>0.77</td>
<td>0.86</td>
<td>0.81</td>
</tr>
<tr class="odd">
<td>1592</td>
<td>-0.35</td>
<td>0.00</td>
<td>-0.19</td>
<td>0.05</td>
<td>0.10</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>1597</td>
<td>-0.49</td>
<td>0.36</td>
<td>-0.13</td>
<td>0.25</td>
<td>0.66</td>
<td>0.33</td>
</tr>
<tr class="odd">
<td>1678</td>
<td>0.54</td>
<td>0.72</td>
<td>0.61</td>
<td>0.73</td>
<td>0.85</td>
<td>0.79</td>
</tr>
<tr class="even">
<td>1722</td>
<td>0.30</td>
<td>0.62</td>
<td>0.51</td>
<td>0.69</td>
<td>0.79</td>
<td>0.77</td>
</tr>
<tr class="odd">
<td>1723</td>
<td>0.46</td>
<td>0.56</td>
<td>0.53</td>
<td>0.70</td>
<td>0.75</td>
<td>0.73</td>
</tr>
</tbody>
</table>
<p>The global column is the random-split model. Local models do best in every batch. They use 2 to 15 components. The pooled model uses 12 components and reaches an overall R² of 0.81, an RMSE of 0.87 ‰ and a within-batch R² of 0.41.</p>
<p>Batch 1678 ranks well with its own local model (r = 0.85) and not at all when left out of the global model (r = 0.04). Its relationship between spectra and δ13C differs from the other batches. Batch 1597 shows the same pattern, less strongly.</p>
<p>Batch 1592 shows no signal, even with its own local model. It has the smallest δ13C spread of all batches, with a standard deviation of 0.85 ‰. Measurement error in the lab values could account for much of that spread.</p>
<p>The tables and plots are in the <a href="./pls.html">PLS notebook</a>.</p>
</section>
</section>
<section id="what-this-means-for-each-use-case" class="level2">
<h2 class="anchored" data-anchor-id="what-this-means-for-each-use-case">What this means for each use case</h2>
<ul>
<li><strong>Ranking samples within a trial, with lab values for some of its samples.</strong> This works. Local models reach r = 0.65 to 0.86 in six batches. The pooled model reaches r = 0.33 to 0.81 in the same six batches and needs fewer lab values per batch.</li>
<li><strong>Ranking samples in a new trial with no lab values.</strong> This works for some batches and fails for others. The data don’t show in advance which group a new batch falls into.</li>
<li><strong>Predicting the δ13C level of a new trial.</strong> This doesn’t work. The spectra don’t carry the batch level in a form that transfers.</li>
</ul>
</section>
<section id="open-questions-and-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="open-questions-and-next-steps">Open questions and next steps</h2>
<ol type="1">
<li><strong>Batch metadata.</strong> The growing conditions, dates, genotypes and sample preparation of each batch could explain why 1678 and 1597 differ from the rest, and why 1722 and 1723 form their own spectral group. If genotypes repeat across batches, we can test whether the spectra rank genotypes the same way across conditions.</li>
<li><strong>Lab repeatability of δ13C.</strong> This decides whether batch 1592 lacks signal or only lacks spread.</li>
<li><strong>Water vapour correction.</strong> Subtracting a reference vapour spectrum would also remove the lines between 1800 and 1300 cm⁻¹. If the instrument software kept the single-beam spectra, its atmospheric compensation may be cleaner.</li>
<li><strong>Nested cross-validation.</strong> Choosing the number of components in an inner loop gives unbiased scores.</li>
<li><strong>Other models.</strong> Memory-based learning or Cubist are worth a bounded test after steps 1 to 4. They must beat PLS on the within-batch scores and on leave-one-batch-out ranking, not on the random split.</li>
</ol>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<ul>
<li><a href="./data.html">00_data</a> loads and aligns the two files.</li>
<li><a href="./eda.html">01_eda</a> covers δ13C by batch, the PCA, the loadings and the water vapour index.</li>
<li><a href="./pls.html">02_pls</a> covers the global, local and pooled PLS models.</li>
</ul>
<p>The random split uses <code>StratifiedKFold(5, shuffle=True, random_state=0)</code>, stratified by batch. The local models use <code>KFold(5, shuffle=True, random_state=0)</code> inside each batch. Leave-one-batch-out uses <code>LeaveOneGroupOut</code>. All models use <code>soilspectfm</code> preprocessing and scikit-learn <code>PLSRegression(scale=False)</code>. The data files are not part of the repository.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/franckalbinet\.github\.io\/cassava");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/franckalbinet/cassava/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>