# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cassava',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/cassava',
                'lib_path': 'cassava'},
  'syms': { 'cassava.data': { 'cassava.data.batch_of': ('data.html#batch_of', 'cassava/data.py'),
                              'cassava.data.load_c13': ('data.html#load_c13', 'cassava/data.py'),
                              'cassava.data.load_data': ('data.html#load_data', 'cassava/data.py'),
                              'cassava.data.load_spectra': ('data.html#load_spectra', 'cassava/data.py')}}}
