"""Load MIR spectra and δ13C measurements of cassava leaves

Docs: https://franckalbinet.github.io/cassava/data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto #0
__all__ = ['load_spectra', 'load_c13', 'batch_of', 'load_data']

# %% ../nbs/00_data.ipynb #ef82a977
import numpy as np, pandas as pd
from fastcore.basics import AttrDict
from pathlib import Path

# %% ../nbs/00_data.ipynb #55aa8344
def load_spectra(
    fname, # CSV with one row per wavenumber and one column per sample
):
    "Read MIR absorbance spectra as `(X, ws, ids)`, with one row of `X` per sample"
    df = pd.read_csv(fname, index_col=0)
    return df.values.T, df.index.values, df.columns.to_numpy(str)

# %% ../nbs/00_data.ipynb #e5d9944f
def load_c13(
    fname, # CSV of sample ids and their δ13C (‰)
) -> pd.Series:
    "Read δ13C values as a `Series` indexed by sample id"
    return pd.read_csv(fname, index_col=0).iloc[:, 0].rename('c13')

# %% ../nbs/00_data.ipynb #1c9e005a
def batch_of(
    ids, # Sample ids of the form `<batch>_<sample>`
) -> np.ndarray:
    "Batch of each sample id"
    return np.array([o.split('_')[0] for o in ids])

# %% ../nbs/00_data.ipynb #283af9ba
def load_data(
    path='data', # Folder holding both files
    spectra='specs_trim.csv', # Spectra file name
    c13='all_batches_wet_chem.csv', # δ13C file name
) -> AttrDict:
    "Spectra and δ13C of the samples present in both files"
    path = Path(path)
    X, ws, ids = load_spectra(path/spectra)
    y = load_c13(path/c13)
    keep = np.isin(ids, y.index)
    return AttrDict(X=X[keep], ws=ws, y=y[ids[keep]].values, ids=ids[keep], batch=batch_of(ids[keep]))
